package Sample.model;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.JTextField;
import java.util.random.RandomGenerator;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

public class PHHP extends JFrame {
  private DocumentListener listener = new DocumentListener() {
    @Override
    public void insertUpdate(DocumentEvent p1) {
      update();
    }

    @Override
    public void removeUpdate(DocumentEvent p1) {
      update();
    }

    @Override
    public void changedUpdate(DocumentEvent p1) {
      update();
    }
  };



  private JTextField inputField_a = new JTextField();

  private JTextField outputField_a = new JTextField();

  private RandomGenerator rand = RandomGenerator.of("Random");
  private int delay = 1000;
  private Timer timer;
  private int counter = 3;
  /*package*/ int j = counter;

  /*package*/ ActionListener act = new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent p1) {
      if (j == 0) {
        timer.stop();
        j = counter;
        timer = new Timer(delay, act);
        timer.setInitialDelay(0);
        timer.start();
      } else {
        update();
        j--;
      }
    }
  };

  public PHHP() {
    setTitle("PHHP");
    setLayout(new GridLayout(10, 2));

    inputField_a.getDocument().addDocumentListener(listener);
    add(new JLabel("Temp"));
    add(inputField_a);
    add(new JLabel("TempSim "));
    add(outputField_a);

    update();
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    pack();

    timer = new Timer(delay, act);
    timer.setInitialDelay(0);
    timer.start();

    setVisible(true);
  }

  public void update() {
    int i_a = 0;
    try {
      i_a = rand.nextInt(2) - rand.nextInt(2) + Integer.parseInt(inputField_a.getText());
    } catch (NumberFormatException e) {
    }
    outputField_a.setText("" + (i_a));
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new PHHP();
      }
    });
  }

}
