package Sample.model;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import java.util.random.RandomGenerator;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.GridLayout;
import javax.swing.SwingUtilities;

public class xPHHP extends JFrame {
  private DocumentListener listener = new DocumentListener() {
    @Override
    public void insertUpdate(DocumentEvent p1) {
      update();
    }

    @Override
    public void removeUpdate(DocumentEvent p1) {
      update();
    }

    @Override
    public void changedUpdate(DocumentEvent p1) {
      update();
    }
  };





  private RandomGenerator rand = RandomGenerator.of("Random");
  private int delay = 1000;
  private Timer timer;
  private int counter = 3;
  /*package*/ int j = counter;

  /*package*/ ActionListener act = new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent p1) {
      if (j == 0) {
        timer.stop();
        j = counter;
        timer = new Timer(delay, act);
        timer.setInitialDelay(0);
        timer.start();
      } else {
        update();
        j--;
      }
    }
  };

  public xPHHP() {
    setTitle("xPHHP");
    setLayout(new GridLayout(10, 2));


    update();
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    pack();

    timer = new Timer(delay, act);
    timer.setInitialDelay(0);
    timer.start();

    setVisible(true);
  }

  public void update() {
    try {
    } catch (NumberFormatException e) {
    }
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new xPHHP();
      }
    });
  }

}
