package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_InputField;
  private ConceptPresentation props_InputFieldReference;
  private ConceptPresentation props_OutputField;
  private ConceptPresentation props_PHHP;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.InputField:
        if (props_InputField == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_InputField = cpb.create();
        }
        return props_InputField;
      case LanguageConceptSwitch.InputFieldReference:
        if (props_InputFieldReference == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x16a79f2d7a8d4f36L, 0xae28276960b9e667L, 0x566d5c3e4db52986L, 0x566d5c3e4db52eebL, "field", "", "");
          props_InputFieldReference = cpb.create();
        }
        return props_InputFieldReference;
      case LanguageConceptSwitch.OutputField:
        if (props_OutputField == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("OutputField");
          props_OutputField = cpb.create();
        }
        return props_OutputField;
      case LanguageConceptSwitch.PHHP:
        if (props_PHHP == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_PHHP = cpb.create();
        }
        return props_PHHP;
    }
    return null;
  }
}
