package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SeverityLevel extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SeverityLevel() {
    super(0x16a79f2d7a8d4f36L, 0xae28276960b9e667L, 0xab3ad991555741dL, "SeverityLevel", "r:66d9b93c-f562-4f88-af54-ce6ee3a9563c(NewLanguage.structure)/771150834210010141");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_normal_0 = new EnumerationDescriptor.MemberDescriptor("normal", "normal", 0xab3ad991555741eL, "r:66d9b93c-f562-4f88-af54-ce6ee3a9563c(NewLanguage.structure)/771150834210010142");
  private final EnumerationDescriptor.MemberDescriptor myMember_warning_0 = new EnumerationDescriptor.MemberDescriptor("warning", "warning", 0xab3ad9915557866L, "r:66d9b93c-f562-4f88-af54-ce6ee3a9563c(NewLanguage.structure)/771150834210011238");
  private final EnumerationDescriptor.MemberDescriptor myMember_critical_0 = new EnumerationDescriptor.MemberDescriptor("critical", "critical", 0xab3ad991555791eL, "r:66d9b93c-f562-4f88-af54-ce6ee3a9563c(NewLanguage.structure)/771150834210011422");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x16a79f2d7a8d4f36L, 0xae28276960b9e667L, 0xab3ad991555741dL, 0xab3ad991555741eL, 0xab3ad9915557866L, 0xab3ad991555791eL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_normal_0, myMember_warning_0, myMember_critical_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_normal_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "normal":
        return myMember_normal_0;
      case "warning":
        return myMember_warning_0;
      case "critical":
        return myMember_critical_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
