package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int LogEntry = 1;
  public static final int Logger = 2;
  public static final int Measurement = 3;
  public static final int MeasurementReference = 4;
  public static final int PHHP = 5;
  public static final int TriggerRule = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x16a79f2d7a8d4f36L, 0xae28276960b9e667L);
    builder.put(0xab3ad9915390ee8L, Action);
    builder.put(0xab3ad991553dfabL, LogEntry);
    builder.put(0xab3ad99155567eeL, Logger);
    builder.put(0xab3ad99153fd70fL, Measurement);
    builder.put(0xab3ad99153fe343L, MeasurementReference);
    builder.put(0x566d5c3e4db17b4aL, PHHP);
    builder.put(0xab3ad99155569e4L, TriggerRule);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
