package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int InputField = 0;
  public static final int InputFieldReference = 1;
  public static final int OutputField = 2;
  public static final int PHHP = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x16a79f2d7a8d4f36L, 0xae28276960b9e667L);
    builder.put(0x566d5c3e4db445caL, InputField);
    builder.put(0x566d5c3e4db52986L, InputFieldReference);
    builder.put(0x566d5c3e4db490c8L, OutputField);
    builder.put(0x566d5c3e4db17b4aL, PHHP);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
