package RMLL.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int InputField = 1;
  public static final int InputFieldReference = 2;
  public static final int LogEntry = 3;
  public static final int Logger = 4;
  public static final int Measurement = 5;
  public static final int MeasurementReference = 6;
  public static final int OutputField = 7;
  public static final int RMLL = 8;
  public static final int TriggerRule = 9;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x16a79f2d7a8d4f36L, 0xae28276960b9e667L);
    builder.put(0xab3ad9915390ee8L, Action);
    builder.put(0x566d5c3e4db445caL, InputField);
    builder.put(0x566d5c3e4db52986L, InputFieldReference);
    builder.put(0xab3ad991553dfabL, LogEntry);
    builder.put(0x101a5652d8a518f8L, Logger);
    builder.put(0xab3ad99153fd70fL, Measurement);
    builder.put(0xab3ad99153fe343L, MeasurementReference);
    builder.put(0x566d5c3e4db490c8L, OutputField);
    builder.put(0x566d5c3e4db17b4aL, RMLL);
    builder.put(0xab3ad99155569e4L, TriggerRule);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
